networks:
  dev-patroni:

services:
  haproxy:
    image: haproxy
    container_name: ivory-dev-patroni-haproxy
    networks: [ dev-patroni ]
    ports:
      - "18008:18008" # patroni general port
      - "18404:18404" # haproxy statistic
      - "18001-18005:18001-18005" # patroni ports
      - "15001-15005:15001-15005" # postgres ports
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  patroni1:
    build: .
    image: dev-patroni
    container_name: ivory-dev-patroni1
    networks: [ dev-patroni ]
    environment:
      PATRONI_NAME: "ivory-dev-patroni1"
      PATRONI_POSTGRESQL_LISTEN: "patroni1:15001"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni1:15001"
      PATRONI_RESTAPI_LISTEN: "patroni1:18001"
      PATRONI_RAFT_SELF_ADDR: "patroni1:2221"
      PATRONI_RAFT_PARTNER_ADDRS: "'patroni2:2222','patroni3:2223'"

  patroni2:
    image: dev-patroni
    container_name: ivory-dev-patroni2
    networks: [ dev-patroni ]
    environment:
      PATRONI_NAME: "ivory-dev-patroni2"
      PATRONI_POSTGRESQL_LISTEN: "patroni2:15002"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni2:15002"
      PATRONI_RESTAPI_LISTEN: "patroni2:18002"
      PATRONI_RAFT_SELF_ADDR: "patroni2:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'patroni1:2221','patroni3:2223'"

  patroni3:
    image: dev-patroni
    container_name: ivory-dev-patroni3
    networks: [ dev-patroni ]
    environment:
      PATRONI_NAME: "ivory-dev-patroni3"
      PATRONI_POSTGRESQL_LISTEN: "patroni3:15003"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni3:15003"
      PATRONI_RESTAPI_LISTEN: "patroni3:18003"
      PATRONI_RAFT_SELF_ADDR: "patroni3:2223"
      PATRONI_RAFT_PARTNER_ADDRS: "'patroni1:2221','patroni2:2222'"

  patroni-cert:
    image: dev-patroni
    container_name: ivory-dev-patroni-cert
    networks: [ dev-patroni ]
    environment:
      PATRONI_NAME: "ivory-dev-patroni-cert"
      PATRONI_POSTGRESQL_LISTEN: "patroni-cert:15004"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni-cert:15004"
      PATRONI_RESTAPI_LISTEN: "patroni-cert:18004"
      PATRONI_RAFT_SELF_ADDR: "patroni-cert:2224"
      PATRONI_RESTAPI_CAFILE: "/opt/certs/ca/ca.crt"
      PATRONI_RESTAPI_CERTFILE: "/opt/certs/server/server.crt"
      PATRONI_RESTAPI_KEYFILE: "/opt/certs/server/server.key"
      PATRONI_RESTAPI_VERIFY_CLIENT: "required"

  patroni-pass:
    image: dev-patroni
    container_name: ivory-dev-patroni-pass
    networks: [ dev-patroni ]
    environment:
      PATRONI_NAME: "ivory-dev-patroni-pass"
      PATRONI_POSTGRESQL_LISTEN: "patroni-pass:15005"
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: "patroni-pass:15005"
      PATRONI_RESTAPI_LISTEN: "patroni-pass:18005"
      PATRONI_RAFT_SELF_ADDR: "patroni-pass:2225"
      PATRONI_RESTAPI_USERNAME: "patroni"
      PATRONI_RESTAPI_PASSWORD: "patroni"
