# These are supported funding model platforms

github: [anselvo] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: anselvo # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://boosty.to/anselvo/purchase/1454406?ssource=DIRECT&share=subscription_link', 'https://patreon.com/anselvo?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
