# These are supported funding model platforms

github: [anselvo] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: anselvo
custom: ['boosty.to/anselvo'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
