name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go:
    name: Build (go)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'

    - name: Build
      working-directory: server
      run: |
        go version
        make build

    - name: Test
      working-directory: server
      run: make test


  javascript:
    name: Build (javascript)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up JavaScript
      uses: actions/setup-node@v7
      with:
        node-version: '26'

    - name: Build
      working-directory: app
      run: |
        node -v
        npm -v
        npm install
        npm run build

    - name: Lint
      working-directory: app
      run: npm run lint

    - name: Test
      working-directory: app
      run: npm run test
